apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-lamp-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: street-lamp-mongodb
  template:
    metadata:
      labels:
        app: street-lamp-mongodb
    spec:
      containers:
        - name: street-lamp-mongodb
          image: mongo:4.4.8
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: street-lamp-mongodb-volume
              mountPath: /data/db
      volumes:
        - name: street-lamp-mongodb-volume
          hostPath:
            path: /db/street_lamp
---
apiVersion: v1
kind: Service
metadata:
  name: street-lamp-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: street-lamp-mongodb
