apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-lamp-data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: street-lamp-data-generator
  template:
    metadata:
      labels:
        app: street-lamp-data-generator
    spec:
      containers:
        - name: street-lamp-data-generator
          image: pipisebastian/data_generator:v3
          env:
            - name: MONGODB_URL
              value: "mongodb://10.43.97.206:27017" # MONGODB IP 수정 필요
            - name: JWT_SECRET_KEY
              value: "key"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name : street-lamp-data-generator
spec:
  selector:
    app: street-lamp-data-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
