apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: smart-trash-can-back
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-trash-can-back
  targetCPUUtilizationPercentage: 50
